import React from 'react'
import type { Metadata } from 'next'
import GalleryLayout from '@/view/gallery/galleryLayout.tsx'
import galleryLayoutTypes from '@/view/gallery/galleryLayout.tsx/galleryLayoutType.d'

export const metadata: Metadata = {
  title: '画廊',
  description: 'Generated by create next app',
}

const GalleryLayoutIndex = ({
  children,
  modal,
}: galleryLayoutTypes.ConfigProps) => {
  return (
    <>
      <GalleryLayout modal={modal}>{children}</GalleryLayout>
      <div id="modal-root"></div>
    </>
  )
}

export default GalleryLayoutIndex
